-- 루시와 엘라 찾기 (LEVEL 2)
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
ORDER BY ANIMAL_ID;

-- 이름에 el이 들어가는 동물 찾기 (LEVEL 2)
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE LOWER(NAME) LIKE '%el%' AND ANIMAL_TYPE LIKE 'Dog'
ORDER BY NAME;

-- 중성화 여부 파악하기 (LEVEL 2)
SELECT ANIMAL_ID, NAME,
      CASE
        WHEN SEX_UPON_INTAKE LIKE 'Spayed%' THEN 'O'
        WHEN SEX_UPON_INTAKE LIKE 'Neutered%' THEN 'O'
        ELSE 'X'
      END 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- 오랜 기간 보호한 동물(2) (LEVEL 3)
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_INS INS INNER JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY (OUTS.DATETIME - INS.DATETIME) DESC
LIMIT 2;

-- DATETIME에서 DATE로 형 변환 (LEVEL 2)
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;